import { existsSync, lstatSync, readFileSync, readdirSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, sep } from "node:path";
import { randomUUID } from "node:crypto";
import { parseFrontmatter } from "@earendil-works/pi-coding-agent";

export const START = "<!-- dynamic-skill -->";
export const END = "<!-- /dynamic-skill -->";
const slug = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export interface SkillNode { name: string; description: string; filePath: string; body: string; children: SkillNode[] }
export interface TreeResult { roots: SkillNode[]; diagnostics: string[] }

export function managedBlock(text: string): { start: number; end: number; text: string } | undefined {
  const starts = [...text.matchAll(/^<!-- dynamic-skill -->\r?$/gm)];
  const ends = [...text.matchAll(/^<!-- \/dynamic-skill -->\r?$/gm)];
  if (!starts.length && !ends.length) return undefined;
  if (starts.length !== 1 || ends.length !== 1 || starts[0]!.index! >= ends[0]!.index!) {
    throw new Error("Malformed dynamic-skill generated block: expected one matching marker pair.");
  }
  const start = starts[0]!.index!;
  const end = ends[0]!.index! + ends[0]![0].length;
  return { start, end, text: text.slice(start, end) };
}

export function validateSkill(text: string, expectedName: string): { name: string; description: string; body: string } {
  if (!/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/.test(text)) {
    throw new Error("SKILL.md requires YAML frontmatter enclosed by --- lines.");
  }
  const { frontmatter, body } = parseFrontmatter(text);
  const { name, description } = frontmatter;
  if (typeof name !== "string" || !slug.test(name) || name.length > 64 || name !== expectedName) {
    throw new Error(`SKILL.md name must match its node name: ${expectedName}`);
  }
  if (typeof description !== "string" || !description.trim() || description.length > 1024) {
    throw new Error("SKILL.md requires a nonblank description of at most 1024 characters.");
  }
  managedBlock(body);
  return { name, description, body };
}

const oneLine = (text: string) => text.replace(/\s+/g, " ").replace(/[\\`*_\[\]<>]/g, "\\$&");
/** Shared node validation for full scans, local refreshes, and LRU eligibility. */
function readSkillNode(filePath: string, expectedName: string) {
  if (basename(dirname(filePath)) !== expectedName) throw new Error(`Skill directory must be named ${expectedName}`);
  const file = lstatSync(filePath);
  if (!file.isFile() || file.isSymbolicLink()) throw new Error("SKILL.md must be a regular file");
  const directory = lstatSync(join(dirname(filePath), "skills"), { throwIfNoEntry: false });
  if (directory && (!directory.isDirectory() || directory.isSymbolicLink())) throw new Error("skills must be a real directory");
  const original = readFileSync(filePath, "utf8");
  return { original, parsed: validateSkill(original, expectedName) };
}

export function renderChildren(children: SkillNode[]): string {
  if (!children.length) return "";
  return [START, "## Child skills", "Auto-generated by dynamic-skill, do not write or edit.", "",
    ...children.map((child) => `- [${child.name}](./skills/${child.name}/SKILL.md): ${oneLine(child.description)}`), END].join("\n");
}

function withChildren(text: string, children: SkillNode[]): string {
  const block = managedBlock(text);
  const newline = text.includes("\r\n") ? "\r\n" : "\n";
  const generated = renderChildren(children).replace(/\n/g, newline);
  if (block) return text.slice(0, block.start) + generated + text.slice(block.end);
  if (!generated) return text;
  return text + (text.endsWith(newline + newline) ? "" : text.endsWith(newline) ? newline : newline + newline) + generated + newline;
}

/** Only traverse skills/<name>/SKILL.md; never follow symlinks inside a tree. */
function synchronizeNodes(targets: { filePath: string; name: string }[], recursive: boolean): TreeResult {
  const diagnostics: string[] = [];
  const visit = (filePath: string, expectedName: string): SkillNode | undefined => {
    // Retry the entire read/scan/patch operation so both parent text and child
    // metadata are refreshed after a conflict. This is optimistic, not a lock.
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const { original, parsed } = readSkillNode(filePath, expectedName);
        const children: SkillNode[] = [];
        const directory = join(dirname(filePath), "skills");
        if (existsSync(directory)) {
          if (!lstatSync(directory).isDirectory() || lstatSync(directory).isSymbolicLink()) throw new Error("skills must be a real directory");
          for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, "en"))) {
            if (entry.name.startsWith(".")) continue;
            const childPath = join(directory, entry.name, "SKILL.md");
            if (!entry.isDirectory() || !slug.test(entry.name) || entry.name.length > 64) {
              diagnostics.push(`${join(directory, entry.name)}: expected a skill directory with a lowercase name`);
              continue;
            }
            if (!existsSync(childPath)) {
              diagnostics.push(`${childPath}: missing; subtree not loaded until its parent skill exists`);
              continue;
            }
            if (recursive) {
              const child = visit(childPath, entry.name);
              if (child) children.push(child);
            } else {
              try {
                const { parsed: child } = readSkillNode(childPath, entry.name);
                children.push({ ...child, filePath: childPath, children: [] });
              } catch (error) {
                diagnostics.push(`${childPath}: ${error instanceof Error ? error.message : String(error)}`);
              }
            }
          }
        }
        // Direct child skill directories outside skills/ are not valid tree nodes.
        for (const entry of readdirSync(dirname(filePath), { withFileTypes: true })) {
          if (entry.name !== "skills" && entry.isDirectory() && existsSync(join(dirname(filePath), entry.name, "SKILL.md"))) {
            diagnostics.push(`${join(dirname(filePath), entry.name)}: child skills must be inside skills/`);
          }
        }
        if (readFileSync(filePath, "utf8") !== original) continue;
        const updated = withChildren(original, children);
        if (updated !== original) {
          const temporary = join(dirname(filePath), `.dynamic-skill-${randomUUID()}.tmp`);
          try {
            writeFileSync(temporary, updated, { flag: "wx", mode: lstatSync(filePath).mode & 0o777 });
            if (readFileSync(filePath, "utf8") !== original) continue;
            renameSync(temporary, filePath);
          } finally {
            if (existsSync(temporary)) unlinkSync(temporary);
          }
        }
        return { ...parsed, body: parseFrontmatter(updated).body, filePath, children };
      } catch (error) {
        diagnostics.push(`${filePath}: ${error instanceof Error ? error.message : String(error)}`);
        return undefined;
      }
    }
    diagnostics.push(`${filePath}: File kept changing during synchronization; generated navigation was not applied. Retry after edits settle.`);
    return undefined;
  };
  const roots = targets.flatMap(({ filePath, name }) => { const node = visit(filePath, name); return node ? [node] : []; });
  return { roots, diagnostics };
}


function validTreePath(root: string, filePath: string): boolean {
  const parts = relative(dirname(root), filePath).split(sep);
  return parts.length % 2 === 1 && parts.slice(0, -1).every((part, i) => i % 2 === 0 ? part === "skills" : slug.test(part) && part.length <= 64);
}

/** Inspect every declared skill, including files outside the valid navigation tree. */
function inspectSkill(root: string, filePath: string): string[] {
  const diagnostics: string[] = [];
  const validPath = validTreePath(root, filePath);
  if (!validPath) diagnostics.push(`${filePath}: Child skills must use skills/<name>/SKILL.md at every level.`);
  let current = dirname(root);
  for (const part of relative(current, filePath).split(sep)) {
    current = join(current, part);
    if (lstatSync(current, { throwIfNoEntry: false })?.isSymbolicLink()) {
      return [...diagnostics, `${filePath}: Symlinked skill nodes are not supported.`];
    }
  }
  const check = (path: string) => {
    try {
      const expectedName = path === root ? "dynamic-skill" : basename(dirname(path));
      readSkillNode(path, expectedName);
    } catch (error) {
      diagnostics.push(`${path}: ${error instanceof Error ? error.message : String(error)}`);
    }
  };
  check(filePath);
  if (validPath) {
    for (let ancestor = filePath; ancestor !== root;) {
      ancestor = join(dirname(dirname(dirname(ancestor))), "SKILL.md");
      check(ancestor);
    }
  }
  return diagnostics;
}

/** Read-only eligibility check used when settling recorded accesses. */
export function isManagedSkill(rootPaths: string[], filePath: string): boolean {
  if (basename(filePath) !== "SKILL.md") return false;
  return rootPaths.some((root) => {
    const rel = relative(dirname(root), filePath);
    if (rel === ".." || rel.startsWith(`..${sep}`) || rel.startsWith(sep)) return false;
    try { return inspectSkill(root, filePath).length === 0; } catch { return false; }
  });
}

/** Direct children of recognized roots, never grandchildren or symlink targets. */
export function listTopLevelSkills(rootPaths: string[]): string[] {
  const paths = new Set<string>();
  for (const root of rootPaths) {
    if (!isManagedSkill(rootPaths, root)) continue;
    const directory = join(dirname(root), "skills");
    if (!existsSync(directory)) continue;
    for (const entry of readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, "en"))) {
      if (!entry.isDirectory()) continue;
      const filePath = join(directory, entry.name, "SKILL.md");
      if (isManagedSkill(rootPaths, filePath)) paths.add(filePath);
    }
  }
  return [...paths];
}

export function synchronizeTrees(rootPaths: string[]): TreeResult {
  const paths = [...new Set(rootPaths)];
  const diagnostics: string[] = [];
  for (const root of paths) {
    const walk = (directory: string) => {
      try {
        for (const entry of readdirSync(directory, { withFileTypes: true })) {
          const path = join(directory, entry.name);
          if (entry.name === "SKILL.md") diagnostics.push(...inspectSkill(root, path));
          if (entry.isDirectory()) walk(path);
        }
      } catch (error) {
        diagnostics.push(`${directory}: ${error instanceof Error ? error.message : String(error)}`);
      }
    };
    walk(dirname(root));
  }
  const result = synchronizeNodes(paths.map((filePath) => ({ filePath, name: "dynamic-skill" })), true);
  return { roots: result.roots, diagnostics: [...new Set([...diagnostics, ...result.diagnostics])] };
}

/** Refresh only the written node and its direct parent, without rewriting other branches. */
export function refreshWrittenSkill(rootPaths: string[], filePath: string): string[] | undefined {
  if (basename(filePath) !== "SKILL.md") return;
  const root = rootPaths.find((path) => {
    const rel = relative(dirname(path), filePath);
    return rel !== ".." && !rel.startsWith(`..${sep}`) && !rel.startsWith(sep);
  });
  if (!root) return;
  const parts = relative(dirname(root), filePath).split(sep);
  const diagnostics = inspectSkill(root, filePath);
  if (!validTreePath(root, filePath)) return diagnostics;
  let current = dirname(root);
  for (const part of parts) {
    current = join(current, part);
    if (lstatSync(current, { throwIfNoEntry: false })?.isSymbolicLink()) return ["Symlinked skill nodes are not supported."];
  }
  const targets = [{ filePath, name: parts.length === 1 ? "dynamic-skill" : parts.at(-2)! }];
  if (parts.length > 1) {
    targets.push({ filePath: join(dirname(dirname(dirname(filePath))), "SKILL.md"), name: parts.length === 3 ? "dynamic-skill" : parts.at(-4)! });
  }
  return [...new Set([...diagnostics, ...synchronizeNodes(targets, false).diagnostics])];
}
